<a href="https://colab.research.google.com/github/Kalana-Lakshan/ML-Self-Learning/blob/main/DS_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

train_data = pd.read_csv('/content/drive/MyDrive/DS Project/SriLanka_Migration_final.csv')

In [11]:
train_data.head()

,date,slbfe_total_annual,slbfe_male_annual,slbfe_female_annual,slbfe_skilled_annual,slbfe_lowskilled_annual,male_skilled_pct_annual,male_lowskilled_pct_annual,female_skilled_pct_annual,female_lowskilled_pct_annual,...,unemployment_rate_annual,employment_ratio_annual,wage_all_workers_annual,central_bank_interest_rate_annual,poverty_rate_annual,CCPI_b2021,PPP_annual,dollar_rate_monthly,dest_gdp_growth_avg_annual,brent_oil_monthly
0,1/1/1994,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,13.03,49.608,712.4,17.0,65.0,14.1362,3260.468925,49.4595,5.599919,14.29
1,2/1/1994,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,13.03,49.608,712.4,17.0,65.0,14.3073,3260.468925,49.1129,5.599919,13.80
2,3/1/1994,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,13.03,49.608,712.4,17.0,65.0,14.3671,3260.468925,48.9308,5.599919,13.82
3,4/1/1994,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,13.03,49.608,712.4,17.0,65.0,14.4793,3260.468925,48.9251,5.599919,15.23
4,5/1/1994,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,13.03,49.608,712.4,17.0,65.0,14.1951,3260.468925,49.0667,5.599919,16.19

In [12]:
train_data.isnull().sum().sum()

np.int64(0)

In [13]:
train_data.nunique()

date                                 384
slbfe_total_annual                    32
slbfe_male_annual                     32
slbfe_female_annual                   32
slbfe_skilled_annual                  32
slbfe_lowskilled_annual               31
male_skilled_pct_annual               32
male_lowskilled_pct_annual            32
female_skilled_pct_annual             32
female_lowskilled_pct_annual          32
avg_age_annual                        28
avg_contract_years_annual             16
top1                                   2
top1_perc                             28
top2                                   4
top2_perc                             26
top3                                   4
top3_perc                             26
top4                                   2
top4_perc                             22
top5                                   5
top5_perc                             25
remittances_annual_usd_mn             32
gdp_usd_bn_annual                     32
inflation_rate_annual                 32
unemployment_rate_annual              31
employment_ratio_annual               32
wage_all_workers_annual               32
central_bank_interest_rate_annual     13
poverty_rate_annual                   32
CCPI_b2021                           359
PPP_annual                            32
dollar_rate_monthly                  382
dest_gdp_growth_avg_annual            32
brent_oil_monthly                    378
dtype: int64

In [14]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384 entries, 0 to 383
Data columns (total 35 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   date                               384 non-null    object
 1   slbfe_total_annual                 384 non-null    int64
 2   slbfe_male_annual                  384 non-null    int64
 3   slbfe_female_annual                384 non-null    int64
 4   slbfe_skilled_annual               384 non-null    int64
 5   slbfe_lowskilled_annual            384 non-null    int64
 6   male_skilled_pct_annual            384 non-null    float64
 7   male_lowskilled_pct_annual         384 non-null    float64
 8   female_skilled_pct_annual          384 non-null    float64
 9   female_lowskilled_pct_annual       384 non-null    float64
 10  avg_age_annual                     384 non-null    float64
 11  avg_contract_years_annual          384 non-null    float64
 12  top1                               384 non-null    object
 13  top1_perc                          384 non-null    float64
 14  top2                               384 non-null    object
 15  top2_perc                          384 non-null    float64
 16  top3                               384 non-null    object
 17  top3_perc                          384 non-null    float64
 18  top4                               384 non-null    object
 19  top4_perc                          384 non-null    float64
 20  top5                               384 non-null    object
 21  top5_perc                          384 non-null    float64
 22  remittances_annual_usd_mn          384 non-null    float64
 23  gdp_usd_bn_annual                  384 non-null    float64
 24  inflation_rate_annual              384 non-null    float64
 25  unemployment_rate_annual           384 non-null    float64
 26  employment_ratio_annual            384 non-null    float64
 27  wage_all_workers_annual            384 non-null    float64
 28  central_bank_interest_rate_annual  384 non-null    float64
 29  poverty_rate_annual                384 non-null    float64
 30  CCPI_b2021                         384 non-null    float64
 31  PPP_annual                         384 non-null    float64
 32  dollar_rate_monthly                384 non-null    float64
 33  dest_gdp_growth_avg_annual         384 non-null    float64
 34  brent_oil_monthly                  384 non-null    float64
dtypes: float64(24), int64(5), object(6)
memory usage: 105.1+ KB

In [15]:
train_data['date'] = pd.to_datetime(train_data['date'], format='%m/%d/%Y')

train_data['day'] = train_data['date'].dt.day
train_data['month'] = train_data['date'].dt.month
train_data['year'] = train_data['date'].dt.year

In [16]:
num_cols = train_data.select_dtypes(include = np.number).columns
cat_cols = train_data.select_dtypes(include = 'object').columns

In [17]:
num_cols

Index(['slbfe_total_annual', 'slbfe_male_annual', 'slbfe_female_annual',
       'slbfe_skilled_annual', 'slbfe_lowskilled_annual',
       'male_skilled_pct_annual', 'male_lowskilled_pct_annual',
       'female_skilled_pct_annual', 'female_lowskilled_pct_annual',
       'avg_age_annual', 'avg_contract_years_annual', 'top1_perc', 'top2_perc',
       'top3_perc', 'top4_perc', 'top5_perc', 'remittances_annual_usd_mn',
       'gdp_usd_bn_annual', 'inflation_rate_annual',
       'unemployment_rate_annual', 'employment_ratio_annual',
       'wage_all_workers_annual', 'central_bank_interest_rate_annual',
       'poverty_rate_annual', 'CCPI_b2021', 'PPP_annual',
       'dollar_rate_monthly', 'dest_gdp_growth_avg_annual',
       'brent_oil_monthly', 'day', 'month', 'year'],
      dtype='object')

In [18]:
train_data[cat_cols].nunique()

top1    2
top2    4
top3    4
top4    2
top5    5
dtype: int64

In [19]:
train_data[cat_cols]

        top1     top2        top3   top4        top5
0    Colombo  Gampaha  Kurunegala  Kandy    Kalutara
1    Colombo  Gampaha  Kurunegala  Kandy    Kalutara
2    Colombo  Gampaha  Kurunegala  Kandy    Kalutara
3    Colombo  Gampaha  Kurunegala  Kandy    Kalutara
4    Colombo  Gampaha  Kurunegala  Kandy    Kalutara
..       ...      ...         ...    ...         ...
379  Colombo  Gampaha  Kurunegala  Kandy  Batticaloa
380  Colombo  Gampaha  Kurunegala  Kandy  Batticaloa
381  Colombo  Gampaha  Kurunegala  Kandy  Batticaloa
382  Colombo  Gampaha  Kurunegala  Kandy  Batticaloa
383  Colombo  Gampaha  Kurunegala  Kandy  Batticaloa

[384 rows x 5 columns]

In [20]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(handle_unknown = 'ignore',sparse_output = False)
encoded_train_array = ohe.fit_transform(train_data[cat_cols])
encoded_cols = ohe.get_feature_names_out(cat_cols)
encoded_df = pd.DataFrame(encoded_train_array, columns = encoded_cols, index = train_data.index)
train_data_encoded = pd.concat([train_data.drop(cat_cols, axis = 1), encoded_df], axis = 1)

In [21]:
train_data_encoded.head()

,date,slbfe_total_annual,slbfe_male_annual,slbfe_female_annual,slbfe_skilled_annual,slbfe_lowskilled_annual,male_skilled_pct_annual,male_lowskilled_pct_annual,female_skilled_pct_annual,female_lowskilled_pct_annual,...,top3_Gampaha,top3_Kandy,top3_Kurunegala,top4_Gampaha,top4_Kandy,top5_Ampara,top5_Anuradhapura,top5_Batticaloa,top5_Galle,top5_Kalutara
0,1994-01-01,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,1994-02-01,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,1994-03-01,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,1994-04-01,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,1994-05-01,60168,16377,43791,51344,8824,50.2,49.8,89.5,10.5,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [22]:
train_data_encoded = train_data_encoded.drop("date",axis = 1)

In [52]:
#1994-2019 seperated for training
X = train_data_encoded.drop('remittances_annual_usd_mn',axis = 1)[0:312]
y = train_data['remittances_annual_usd_mn'][0:312]

In [53]:
X['month']

0       1
1       2
2       3
3       4
4       5
       ..
307     8
308     9
309    10
310    11
311    12
Name: month, Length: 312, dtype: int32

In [49]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [25]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators = 50,
    max_depth = 5,

)

model.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=50,
             n_jobs=None, num_parallel_tree=None, ...)

In [26]:
y_predict = model.predict(X_test)

In [27]:
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score

In [28]:
print('MSE: ',mean_squared_error(y_test,y_predict))
print('MAE: ',mean_absolute_error(y_test,y_predict))
print('R2 Score: ',r2_score(y_test,y_predict))

MSE:  1.851059952388041e-07
MAE:  0.00038978873788602704
R2 Score:  0.9999999999999726

In [32]:
n = X_test.shape[0]
p = X_test.shape[1]

r2 = r2_score(y_test, y_predict)

# Adjusted R2
adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)
print("Adjusted R2:", adj_r2)

Adjusted R2: 0.9999999999999256

In [33]:
#using lasso regression
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [34]:
from sklearn.linear_model import LassoCV

lasso = LassoCV(cv=5, random_state=42)
lasso.fit(X_train_scaled, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.239e+05, tolerance: 1.994e+05
  model = cd_fast.enet_coordinate_descent(

LassoCV(cv=5, random_state=42)

In [35]:
print("Best alpha:", lasso.alpha_)

Best alpha: 2.494128428299252

In [36]:
y_pred = lasso.predict(X_test_scaled)

In [37]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

n = X_test.shape[0]
p = X_test.shape[1]

adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

print("R2:", r2)
print("Adjusted R2:", adj_r2)

R2: 0.9977974319184381
Adjusted R2: 0.9940216009214747

In [41]:
import numpy as np

selected_features = np.array(X.columns.to_list())[lasso.coef_ != 0]

print("Selected features:", selected_features)

Selected features: ['slbfe_total_annual' 'slbfe_male_annual' 'male_skilled_pct_annual'
 'male_lowskilled_pct_annual' 'female_skilled_pct_annual'
 'female_lowskilled_pct_annual' 'avg_age_annual'
 'avg_contract_years_annual' 'top2_perc' 'top3_perc' 'top5_perc'
 'gdp_usd_bn_annual' 'inflation_rate_annual' 'unemployment_rate_annual'
 'employment_ratio_annual' 'wage_all_workers_annual'
 'central_bank_interest_rate_annual' 'dest_gdp_growth_avg_annual'
 'brent_oil_monthly' 'year' 'top2_Kurunegala' 'top3_Kandy' 'top5_Ampara'
 'top5_Batticaloa' 'top5_Galle' 'top5_Kalutara']

In [42]:
len(X.columns.to_list())

48

In [43]:
len(selected_features)

26